<%
require 'yaml'
formula = YAML.load_file('metadata.yml')
formula_name = formula['name']
%>
---

driver:
  name: vagrant
  hostname: freebsd.ci.local
  linked_clone: true
  cache_directory: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_options: -p git -p curl -p ca_root_nss -p py36-pip -p python
  salt_version: latest
  <% if ENV['SALT_BOOTSTRAP_URL'] %>
  salt_bootstrap_url: <%= ENV['SALT_BOOTSTRAP_URL'] %>
  <% end %>
  salt_copy_filter:
    - .kitchen
    - .git
    - .ssh
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  salt_version: latest
  pillars-from-files:
    <%= formula_name %>.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - <%= formula_name %>
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: <%= formula_name %>
  state_top:
    base:
      '*':
        - <%= formula_name %>

platforms:
  - name: freebsd-11.2
  - name: freebsd-12.0

suites:
  - name: default
